classDiagram
    class Field {
        +int height
        +int width
        +list[list[int]] base_point
        +list[list[str]] status
        +list[str] team
        +calc_point(): dict[str, int]
        +build_castle(): None
        +fill(): None
        +update(): None
        +judge_castle(): list[list[tuple[int]]]
        +judge_zone(): list[tuple[int]]
    }
