classDiagram
    Field -- Judge
    class Field {
        +int height
        +int width
        +list[list[int]] base_point
        +list[list[str]] status
    }
    class Judge {
        +Field field
        +tuple[str, str] teams
        +tuple[str, str] wall_mark
        +tuple[str, str] zone_mark
        +calc_point(): dict[str, int]
        +build_castle(): None
        +fill(): None
        +update(): None
        +judge_castle(): dict[str, list[list[tuple[int, int]]]]
        +judge_zone(): dict[str, set[tuple[int, int]]]
    }
